<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Stagem Team
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Stagem
 * @package Stagem_ZfcSystem
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>

<div class="menu-left-drop-down">
	<ul class="level-0">
		<li>
			<a href="#">Настройки</a>
		</li>
	</ul>
	<ul class="level-1">
		<li><a href="/store/update-price-list">Актуализировать цены</a></li>
		<li><a href="/users/monitoring">Мониторинг пользователей</a></li>
		<li><a href="/spare/index">ВиражЗапчасти</a></li>
		<li><a href="/discount/index">Программа лояльности</a></li>
		<li><a href="#" class="active-a">Настройки системы</a><span class="figure arrow-up"></span>
			<ul class="level-2 active-ul">
				<li><a href="/mail/index">Письма</a></li>
				<li><a href="/roles/index">Роли</a></li>
				<li><a href="/users/index">Управление пользователями</a></li>
				<li><a href="/job-titles/index">Должности</a></li>
				<li><a href="/users/change-password">Личные данные</a></li>
				<li><a href="/status/index">Статусы</a></li>
			</ul>
		</li>
		<li><a href="#" class="active-a">Автомобили</a><span class="figure arrow-up"></span>
			<ul class="level-2 active-ul">
				<li><a href="/brand/index">Марки машин</a></li>
				<li><a href="/car-model/index">Модели</a></li>
				<li><a href="/car-subgroup/index">Подгрупы авто</a></li>
				<li><a href="/car-equipment/index">Комплектации</a></li>
				<li><a href="/car-assembly/index">Сборка авто</a></li>
			</ul>
		</li>
		<li><a href="/supplier/index">Поставщики</a></li>
		<li><a href="/ra-supplier/index">Поставщики РАЗ</a></li>
		<li><a href="#" class="active-a">Перевозки</a><span class="figure arrow-up"></span>
			<ul class="level-2 active-ul">
				<li><a href="/autocarts/index">Автовозы</a></li>
				<li><a href="/autocarts-forwarder/index">Экспедиторы</a></li>
				<li><a href="/type-autocarts/index">Типи перевозки</a></li>
			</ul>
		</li>
		<li><a href="#" class="active-a">Клиенты</a><span class="figure arrow-up"></span>
			<ul class="level-2 active-ul">
				<li><a href="/buyers/index">Покупатели</a></li>
				<li><a href="/authorized-persons/index">Уполномоченные лица</a></li>
			</ul>
		</li>
		<li><a href="/optional-equipment/index">Дополнительное оборудование и аксессуары</a></li>
		<li><a href="#">Отделения</a><span class="figure arrow-down"></span>
			<ul class="level-2">
				<li><a href="/regions/index">Области</a></li>
				<li><a href="/towns/index">Города</a></li>
				<li><a href="/city/index">Склады-продаж</a>
					<div class="notification">40</div>
				</li>
				<li><a href="/dealerships/index">Дилерские центры</a></li>
				<li><a href="/department/index">Отдел</a></li>
			</ul>
		</li>
		<li><a href="#">Способ покупки</a><span class="figure arrow-down"></span>
			<ul class="level-2">
				<li><a href="/vidy-oplat/index">Виды оплат</a></li>
				<li><a href="/vidy-lizinga/index">Виды лизинга</a></li>
				<li><a href="/vidy-kreditov/index">Виды кредитов</a></li>
				<li><a href="/vidy-rassrochek/index">Виды рассрочек</a></li>
				<li><a href="/car-action/index">Акции</a></li>
			</ul>
		</li>
		<li><a href="#">Приказы и распоряжения</a><span class="figure arrow-down"></span>
			<ul class="level-2">
				<li><a href="/category/index">Разделы в приказах и распоряжениях</a></li>
			</ul>
		</li>
		<li><a href="#">CRM</a><span class="figure arrow-down"></span>
			<ul class="level-2">
				<li><a href="/customer-response/index">Ответ клиента</a></li>
			</ul>
		</li>
		<li><a href="/spares/index">Запчасти</a></li>
		<li><a href="/promotional-products/index">Рекламная продукция</a></li>
	</ul>
</div>