<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_<package>
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
/** @var \Stagem\ZfcSystem\Config\Form\ConfigForm $form */
$form = $this->vars('form');
$form->setAttribute('action', $this->url('admin/default', [
    'controller' => $this->current('controller'),
    'action' => $this->current('action'),
    'id' => 0,
    'more' => 'section/' . $form->getOptions()['section'],
]));

#$form->setAttribute('class','form-horizontal');
$form->prepare();
?>

<div class="row">
    <div class="col-md-12">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-body">
                <? //= $this->form(null, null)->openTag($form) ?>
                <?= $this->form()->openTag($form) ?>
                <?= $this->formCollection($form) ?>

                <!--<div class="box-footer">
                    <? /*= $this->formElement($form->get('submit'))*/ ?>
				</div>-->
                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</div>